name = "image-gallery"
main = "worker.js"
compatibility_date = "2024-11-20"

[site]
bucket = "./dist"

# Uncomment and configure if you want to use a custom domain
# routes = [
#   { pattern = "yourdomain.com/*", zone_name = "yourdomain.com" }
# ]
